# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('up_votes', models.PositiveIntegerField(default=0)),
                ('down_votes', models.PositiveIntegerField(default=0)),
                ('_lower_bound', models.FloatField(default=0)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('parent', models.PositiveIntegerField(null=True)),
                ('path', models.TextField(null=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
    ]
