# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog_id',
            field=models.PositiveIntegerField(default=-1),
        ),
    ]
