# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('honor', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.URLField(default=b'http://www.theblogstarter.com/wp-content/uploads/2016/01/start-your-blog-4-steps.png')),
                ('body', models.TextField()),
                ('created', models.DateField(default=datetime.datetime(2016, 6, 25, 17, 30, 54, 690000))),
                ('hidden', models.BooleanField(default=True)),
                ('authors', models.ManyToManyField(to='blog.Author')),
            ],
        ),
    ]
