# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 19:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160625_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateField(default=datetime.datetime(2016, 6, 25, 21, 45, 31, 770000)),
        ),
    ]
