# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 14:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160628_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateField(default=datetime.datetime(2016, 6, 28, 16, 30, 32, 44309)),
        ),
    ]
